// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "go-challenge-agenda/services/agenda/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReservationRepository is an autogenerated mock type for the ReservationRepository type
type ReservationRepository struct {
	mock.Mock
}

type ReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReservationRepository) EXPECT() *ReservationRepository_Expecter {
	return &ReservationRepository_Expecter{mock: &_m.Mock}
}

// CancelReservation provides a mock function with given fields: ctx, id
func (_m *ReservationRepository) CancelReservation(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReservationRepository_CancelReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelReservation'
type ReservationRepository_CancelReservation_Call struct {
	*mock.Call
}

// CancelReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReservationRepository_Expecter) CancelReservation(ctx interface{}, id interface{}) *ReservationRepository_CancelReservation_Call {
	return &ReservationRepository_CancelReservation_Call{Call: _e.mock.On("CancelReservation", ctx, id)}
}

func (_c *ReservationRepository_CancelReservation_Call) Run(run func(ctx context.Context, id string)) *ReservationRepository_CancelReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReservationRepository_CancelReservation_Call) Return(_a0 error) *ReservationRepository_CancelReservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReservationRepository_CancelReservation_Call) RunAndReturn(run func(context.Context, string) error) *ReservationRepository_CancelReservation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReservation provides a mock function with given fields: ctx, r
func (_m *ReservationRepository) CreateReservation(ctx context.Context, r *domain.Reservation) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Reservation) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReservationRepository_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type ReservationRepository_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - r *domain.Reservation
func (_e *ReservationRepository_Expecter) CreateReservation(ctx interface{}, r interface{}) *ReservationRepository_CreateReservation_Call {
	return &ReservationRepository_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, r)}
}

func (_c *ReservationRepository_CreateReservation_Call) Run(run func(ctx context.Context, r *domain.Reservation)) *ReservationRepository_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Reservation))
	})
	return _c
}

func (_c *ReservationRepository_CreateReservation_Call) Return(_a0 error) *ReservationRepository_CreateReservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReservationRepository_CreateReservation_Call) RunAndReturn(run func(context.Context, *domain.Reservation) error) *ReservationRepository_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservation provides a mock function with given fields: ctx, id
func (_m *ReservationRepository) GetReservation(ctx context.Context, id string) (*domain.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 *domain.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReservationRepository_GetReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservation'
type ReservationRepository_GetReservation_Call struct {
	*mock.Call
}

// GetReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReservationRepository_Expecter) GetReservation(ctx interface{}, id interface{}) *ReservationRepository_GetReservation_Call {
	return &ReservationRepository_GetReservation_Call{Call: _e.mock.On("GetReservation", ctx, id)}
}

func (_c *ReservationRepository_GetReservation_Call) Run(run func(ctx context.Context, id string)) *ReservationRepository_GetReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReservationRepository_GetReservation_Call) Return(_a0 *domain.Reservation, _a1 error) *ReservationRepository_GetReservation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReservationRepository_GetReservation_Call) RunAndReturn(run func(context.Context, string) (*domain.Reservation, error)) *ReservationRepository_GetReservation_Call {
	_c.Call.Return(run)
	return _c
}

// ListReservations provides a mock function with given fields: ctx, doctorID, patientID, from, to
func (_m *ReservationRepository) ListReservations(ctx context.Context, doctorID string, patientID string, from time.Time, to time.Time) ([]*domain.Reservation, error) {
	ret := _m.Called(ctx, doctorID, patientID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListReservations")
	}

	var r0 []*domain.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]*domain.Reservation, error)); ok {
		return rf(ctx, doctorID, patientID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []*domain.Reservation); ok {
		r0 = rf(ctx, doctorID, patientID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, doctorID, patientID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReservationRepository_ListReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReservations'
type ReservationRepository_ListReservations_Call struct {
	*mock.Call
}

// ListReservations is a helper method to define mock.On call
//   - ctx context.Context
//   - doctorID string
//   - patientID string
//   - from time.Time
//   - to time.Time
func (_e *ReservationRepository_Expecter) ListReservations(ctx interface{}, doctorID interface{}, patientID interface{}, from interface{}, to interface{}) *ReservationRepository_ListReservations_Call {
	return &ReservationRepository_ListReservations_Call{Call: _e.mock.On("ListReservations", ctx, doctorID, patientID, from, to)}
}

func (_c *ReservationRepository_ListReservations_Call) Run(run func(ctx context.Context, doctorID string, patientID string, from time.Time, to time.Time)) *ReservationRepository_ListReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *ReservationRepository_ListReservations_Call) Return(_a0 []*domain.Reservation, _a1 error) *ReservationRepository_ListReservations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReservationRepository_ListReservations_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]*domain.Reservation, error)) *ReservationRepository_ListReservations_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservation provides a mock function with given fields: ctx, r
func (_m *ReservationRepository) UpdateReservation(ctx context.Context, r *domain.Reservation) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Reservation) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReservationRepository_UpdateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservation'
type ReservationRepository_UpdateReservation_Call struct {
	*mock.Call
}

// UpdateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - r *domain.Reservation
func (_e *ReservationRepository_Expecter) UpdateReservation(ctx interface{}, r interface{}) *ReservationRepository_UpdateReservation_Call {
	return &ReservationRepository_UpdateReservation_Call{Call: _e.mock.On("UpdateReservation", ctx, r)}
}

func (_c *ReservationRepository_UpdateReservation_Call) Run(run func(ctx context.Context, r *domain.Reservation)) *ReservationRepository_UpdateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Reservation))
	})
	return _c
}

func (_c *ReservationRepository_UpdateReservation_Call) Return(_a0 error) *ReservationRepository_UpdateReservation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReservationRepository_UpdateReservation_Call) RunAndReturn(run func(context.Context, *domain.Reservation) error) *ReservationRepository_UpdateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// NewReservationRepository creates a new instance of ReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationRepository {
	mock := &ReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
